[project]
name = "gpt_from_scratch"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib", "--maxfail=1", "-s"]

# don't want to recurse evalugator
norecursedirs = ["evalugator"]
